import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  formContainer: { gap: 16 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    padding: 10,
    borderRadius: 8,
    gap: 8,
  },
  errorText: { fontSize: 12 },
  inputGroup: { gap: 6 },
  label: { fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  inputWrapper: { position: 'relative', justifyContent: 'center' },
  inputIcon: { position: 'absolute', left: 12, zIndex: 1 },
  passwordIcon: { position: 'absolute', right: 12, zIndex: 1, padding: 4 },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 12,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 14,
  },
  submitButton: {
    height: 56,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});
