import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContainer: { flexGrow: 1, justifyContent: 'space-between' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
  },
  headerRight: { alignItems: 'flex-end' },
  terminalText: {
    fontSize: 10,
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    color: '#94a3b8',
    marginBottom: 2,
  },
  flotaContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  flotaText: { fontSize: 12, fontWeight: 'bold', color: '#f59e0b' },
  
  mainContent: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
  },
  card: {
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  titleContainer: { marginBottom: 24 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 14 },
  
  quickSelectSection: { marginBottom: 20 },
  quickSelectGrid: { flexDirection: 'row', gap: 8 },
  quickOpButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
  },
  quickOpSelected: {
    borderColor: '#00A3E0',
    backgroundColor: 'rgba(0, 163, 224, 0.15)',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarSelected: { backgroundColor: '#00A3E0' },
  avatarUnselected: { backgroundColor: '#334155' },
  avatarText: { color: '#fff', fontSize: 12, fontWeight: 'bold' },
  quickOpInfo: { flex: 1 },
  quickOpName: { fontSize: 12, fontWeight: 'bold' },
  quickOpRut: { fontSize: 10, fontFamily: 'monospace' },
  
  formContainer: { gap: 16 },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(244, 63, 94, 0.15)',
    borderColor: 'rgba(244, 63, 94, 0.4)',
    borderWidth: 1,
    padding: 10,
    borderRadius: 8,
    gap: 8,
  },
  errorText: { color: '#f87171', fontSize: 12 },
  inputGroup: { gap: 6 },
  label: { fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  inputWrapper: { position: 'relative', justifyContent: 'center' },
  inputIcon: { position: 'absolute', left: 12, zIndex: 1 },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 12,
    paddingLeft: 40,
    paddingRight: 12,
    fontSize: 14,
  },
  submitButton: {
    height: 56,
    backgroundColor: '#00A3E0',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
    shadowColor: '#00A3E0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  
  dividerContainer: { marginVertical: 24, alignItems: 'center', justifyContent: 'center' },
  dividerLine: { position: 'absolute', width: '100%', borderTopWidth: 1 },
  dividerTextWrapper: { paddingHorizontal: 10 },
  dividerText: { fontSize: 11, textTransform: 'uppercase', color: '#94a3b8' },
  
  msButton: {
    height: 52,
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  msLogo: { width: 18, height: 18, gap: 1 },
  msLogoRow: { flexDirection: 'row', flex: 1, gap: 1 },
  msLogoSquare: { flex: 1 },
  msButtonText: { fontSize: 14, fontWeight: 'bold' },
  
  offlineNotice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 8,
  },
  offlineLeft: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  offlineText: { fontSize: 11, color: '#94a3b8' },
  networkStatusText: { fontSize: 11, fontFamily: 'monospace', color: '#94a3b8' },
  
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
  },
  footerRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  footerText: { fontSize: 11, color: '#94a3b8' },
  
  textWhite: { color: '#fff' },
  textWhiteOpacity: { color: 'rgba(255,255,255,0.7)' },
});

export const darkTheme = StyleSheet.create({
  background: { backgroundColor: '#0A1017' },
  cardBackground: { backgroundColor: '#101824' },
  cardBorder: { borderColor: '#1e293b' },
  borderBottom: { borderBottomColor: '#1e293b' },
  borderTop: { borderTopColor: '#1e293b' },
  textPrimary: { color: '#ffffff' },
  textSecondary: { color: '#94a3b8' },
  textTertiary: { color: '#64748b' },
  inputBackground: { backgroundColor: '#0B121C', borderColor: '#334155' },
  quickOpUnselected: { backgroundColor: 'rgba(15, 23, 42, 0.6)', borderColor: '#1e293b' },
  msButtonTheme: { backgroundColor: 'rgba(15, 23, 42, 0.8)', borderColor: '#334155' },
});

export const lightTheme = StyleSheet.create({
  background: { backgroundColor: '#f1f5f9' },
  cardBackground: { backgroundColor: '#ffffff' },
  cardBorder: { borderColor: '#e2e8f0' },
  borderBottom: { borderBottomColor: '#e2e8f0' },
  borderTop: { borderTopColor: '#e2e8f0' },
  textPrimary: { color: '#0f172a' },
  textSecondary: { color: '#64748b' },
  textTertiary: { color: '#94a3b8' },
  inputBackground: { backgroundColor: '#f8fafc', borderColor: '#cbd5e1' },
  quickOpUnselected: { backgroundColor: '#f8fafc', borderColor: '#e2e8f0' },
  msButtonTheme: { backgroundColor: '#ffffff', borderColor: '#cbd5e1' },
});
